### ISSUE TITLE
ImportError: No module named applicationinsights

### ISSUE THREAD

**Issue by irvinec** [Azure-Samples/iot-hub-python-raspberrypi-client-app#19]
After following the steps in the README and trying to run the sample app I get:

```
$ python app.py
Traceback (most recent call last):
  File "app.py", line 17, in <module>
    from telemetry import Telemetry
  File "/home/casey/iot-py-sample/telemetry.py", line 2, in <module>
    from applicationinsights import TelemetryClient
ImportError: No module named applicationinsights
```
```
$ python --version
Python 2.7.13
```

I'm guessing we just need to clone the applicationinsights repo and install that as well.

**Comment by irvinec** [comment]
Looks like this is because I have python 3.7 installed from source on my Pi.
(setup.sh already has code to install applicationinsights.)

```
$ pip --version
pip 18.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

```
$ sudo pip install applicationinsights
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: applicationinsights in /usr/local/lib/python3.7/site-packages (0.11.7)
```

The command I needed to use to install applicationinsights for python version 2.7 was:
```
$ python -m pip install applicationinsights
```

Closing this issue since I think it is pretty specific to my setup.
